SigningServer/SigningServer/Controllers/SignController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using ProxyServer.Data;
using ProxyServer.Models;
using System.Security.Cryptography;
using System.Text;

namespace ProxyServer.Controllers
{
    public class SignController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<HomeController> _logger;
        private readonly RSACryptoServiceProvider RSA;

        public SignController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _context = context;
            _logger = logger;
            RSA = new RSACryptoServiceProvider();

            ProxyServer.Models.ServerKeyPair keypair = _context.ServerKeyPair.ToList()[0];
            string publicKey = keypair.PublicKeyOnly;
            string privatePublicKeys = keypair.PrivatePublicKeyPair;

            RSA.FromXmlString(privatePublicKeys);
        }
        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [Route("/Sign/RequestSignature")]
        public string RequestSignature()
        {
            bool has2fa = _context.Users.Where(user => user.UserName == User.Identity.Name).SingleOrDefault().TwoFactorEnabled;
            if (!has2fa)
            {
                return "NO_2FA";
            }

            StreamReader bodyStream = new StreamReader(HttpContext.Request.Body);
            Task<string> bodyText = bodyStream.ReadToEndAsync();
            bodyText.Wait();

            string digest = bodyText.Result;
            string id = _context.Users.Where(user => user.UserName == User.Identity.Name).SingleOrDefault().Id;
            string username = User.Identity.Name;

            UnicodeEncoding byte_converter = new UnicodeEncoding();
            byte[] digest_bytes = byte_converter.GetBytes(digest);
            byte[] username_bytes = byte_converter.GetBytes(username);

            byte[] to_be_signed = new byte[digest_bytes.Length + username_bytes.Length];
            Buffer.BlockCopy(digest_bytes, 0, to_be_signed, 0, digest_bytes.Length);
            Buffer.BlockCopy(username_bytes, 0, to_be_signed, digest_bytes.Length, username_bytes.Length);

            byte[] signature = RSA.SignData(to_be_signed, SHA256.Create());

            SignatureStatement statement = new SignatureStatement();
            statement.MessageDigest = digest;
            statement.UserId = id;
            statement.Username = username;
            statement.SignedOn = DateTime.Now;
            _context.SignatureStatement.Add(statement);
            _context.SaveChanges();

            string base64signature = Convert.ToBase64String(signature);

            JObject json = JObject.Parse("{ \"signature\" : \"" + base64signature + "\", \"user\": \"" + statement.Username + "\"}");
            _logger.Log(LogLevel.Information, json.ToString());
            return json.ToString();
        }
    }
}

SigningServer/SigningServer/Controllers/VerifyController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using ProxyServer.Data;
using System.Security.Cryptography;
using System.Text;

namespace ProxyServer.Controllers
{
    public class VerifyController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<HomeController> _logger;
        private readonly RSACryptoServiceProvider RSA;

        public VerifyController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _context = context;
            _logger = logger;
            RSA = new RSACryptoServiceProvider();

            ProxyServer.Models.ServerKeyPair keypair = _context.ServerKeyPair.ToList()[0];
            string publicKey = keypair.PublicKeyOnly;
            string privatePublicKeys = keypair.PrivatePublicKeyPair;

            RSA.FromXmlString(privatePublicKeys);
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [Route("/Verify/RequestVerification")]
        public string RequestVerification()
        {
            StreamReader bodyStream = new StreamReader(HttpContext.Request.Body);
            Task<string> bodyText = bodyStream.ReadToEndAsync();
            bodyText.Wait();

            string content = bodyText.Result;

            JObject json = JObject.Parse(content);
            string digest    = (string)json["hashed"];
            string user      = (string)json["user"];
            string signature = (string)json["signature"];
            _logger.Log(LogLevel.Information, "Digest: " + digest);
            _logger.Log(LogLevel.Information, "User: " + user);
            _logger.Log(LogLevel.Information, "Signature: " + signature);

            UnicodeEncoding byte_converter = new UnicodeEncoding();
            byte[] digest_bytes = byte_converter.GetBytes(digest);
            byte[] username_bytes = byte_converter.GetBytes(user);

            byte[] to_be_signed = new byte[digest_bytes.Length + username_bytes.Length];
            Buffer.BlockCopy(digest_bytes, 0, to_be_signed, 0, digest_bytes.Length);
            Buffer.BlockCopy(username_bytes, 0, to_be_signed, digest_bytes.Length, username_bytes.Length);

            string new_signature = Convert.ToBase64String(RSA.SignData(to_be_signed, SHA256.Create()));
            _logger.Log(LogLevel.Information, "Signature from file: " + signature);
            _logger.Log(LogLevel.Information, "New Signature: " + new_signature);

            if (Equals(signature, new_signature))
            {
                _logger.Log(LogLevel.Information, "VERIFIED");
                TempData["signer"] = user;
                return "YES";
            }

            _logger.Log(LogLevel.Information, "NOT VERIFIED");
            return "NO";
        }
    }
}

SigningServer/SigningServer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Signing Server</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
     <link rel="stylesheet" href="~/SigningServer.styles.css" />
    <link href="@Url.Content("~/css/Layout.css")" rel="stylesheet" type="text/css" />@RenderSection("Styles", false)
    <link rel="stylesheet" href="~/css/attachArea.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/js/site.js" asp-append-version="true" />
    <script src="https://kit.fontawesome.com/26c830ab51.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark box-shadow mb-3">
            <div class="container-fluid">
                <img class="img-fluid" src="~/content/server.png"/> 
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Signing Server</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item ms-3">
                            <a class="nav-link text-white fw-bold" asp-area="" asp-controller="Sign" asp-action="Index">Sign</a>
                        </li>
                        <li class="nav-item ms-3">
                            <a class="nav-link text-white fw-bold" asp-area="" asp-controller="Verify" asp-action="Index">Verify</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid container-lg" id="main_content">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-center bg-dark text-white align-items-baseline">
        <div class="container">
            &copy; 2022 - Signing Server</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>